[package]
name = "paeth"
version = "0.1.0"
authors = ["Madison McGaffin <greyhill@gmail.com>"]

[dependencies.nalgebra]
version = "0.8"

[features]
default = []
opencl = ["proust"]

[dependencies.proust]
git = "https://github.com/greyhill/proust"
version = "0.0.5"
optional = true
